# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
#
# Use the following commands to install theia packages (publix github repos)
#   renv::install("2DegreesInvesting/r2dii.climate.stress.test@fix/speed_improvements")
#   renv::install("2DegreesInvesting/stress.test.plot.report")

library(rhino)
library(shiny)
# library(shiny.router)
library(semantic.dashboard)
library(shiny.semantic)
library(arrow)
library(dplyr)
# library(slickR)
# library(shinyWidgets)
library(shinyjs)
# library(plotly)
library(ggplot2)
# library(uuid)
library(DT)
# library(tidytext)
# library(forcats)
# library(mlflow)
# library(gridExtra)
# library(ggpubr)
library(zip)


library(r2dii.climate.stress.test)
library(stress.test.plot.report)
# library(r2dii.colours)
# library(r2dii.plot)
