# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
#
# Use the following commands to install theia packages (publix github repos)
#   renv::install("2DegreesInvesting/trisk.model@fix/speed_improvements")
#   renv::install("2DegreesInvesting/trisk.plots")

library(rhino)
library(shiny)
# library(shiny.router)
library(semantic.dashboard)
library(shiny.semantic)
library(dplyr)
# library(slickR)
# library(shinyWidgets)
library(shinyjs)
# library(plotly)
library(ggplot2)
# library(uuid)
library(DT)
# library(tidytext)
# library(forcats)
# library(mlflow)
# library(gridExtra)
# library(ggpubr)
library(zip)
library(jsonlite)
library(httr)
library(RPostgres)
library(aws.s3)


library(trisk.model)
library(trisk.plots)
# library(r2dii.colours)
# library(r2dii.plot)
